services:
  web:
    build:
      context: ./pycharm_project
      dockerfile: Dockerfile
      platforms:
        - linux/amd64
    ports:
      - "7999:8000"
    volumes:
      - ./pycharm_project:/app
    env_file:
      - .env
    environment:
      GOOGLE_APPLICATION_CREDENTIALS: /app/gcs-credentials.json
      AWS_REGION: ${AWS_REGION}
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
    depends_on:
      - db
    command: >
      sh -c "python manage.py migrate &&
             python manage.py collectstatic --noinput &&
             python manage.py runserver 0.0.0.0:8000"

  db:
    image: postgres:15
    ports:
      - "5431:5432"
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev_user
      POSTGRES_PASSWORD: dev_pass
    volumes:
      - postgres_data:/var/lib/postgresql/data

  react:
    build:
      context: ./react_project
      target: dev
      args:
        NODE_ENV: development
        AISHA_API_BASE: http://localhost:7999/api
    environment:
      NODE_ENV: development
      VITE_AISHA_API_BASE: http://localhost:7999/api
    ports:
      - "5173:5173"
    volumes:
      - ./react_project:/app
      - /app/node_modules
    env_file:
      - .env
    depends_on:
      - web
    command: npm run dev

volumes:
  postgres_data:
