FROM python:3.11-slim

WORKDIR /app

COPY requirements_minimal.txt .
RUN pip install -r requirements_minimal.txt

COPY db_test_minimal.py .

EXPOSE 8080

CMD ["python", "db_test_minimal.py"] 