# Generated by Django 5.2.3 on 2025-06-26 04:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('engine', models.CharField(choices=[('black_forest_labs', 'black_forest_labs'), ('ideogram', 'ideogram'), ('imagen3', 'imagen3'), ('midjourney', 'midjourney')], max_length=255)),
                ('prompt', models.TextField()),
                ('negative_prompt', models.TextField(blank=True)),
                ('credit', models.IntegerField()),
                ('sample_input_img_url', models.URLField(blank=True, default='')),
                ('sample_result_img_url', models.URLField(blank=True, default='')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='menus', to='api.category')),
            ],
        ),
        migrations.CreateModel(
            name='PromptVariable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255)),
                ('key', models.CharField(max_length=255)),
                ('menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prompt_variables', to='api.menu')),
            ],
        ),
    ]
