# Generated by Django 5.2.3 on 2025-07-13 03:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(help_text='MyGarageユーザーID', max_length=100)),
                ('car_id', models.CharField(help_text='MyGarage愛車ID', max_length=100)),
                ('license_plate_text', models.CharField(blank=True, help_text='ナンバープレート文字列（例: 横浜 330 な 2960）', max_length=200, null=True)),
                ('logo_mark_image_url', models.URLField(blank=True, help_text='ロゴマーク画像のS3 URL', null=True)),
                ('original_number_image_url', models.URLField(blank=True, help_text='オリジナルナンバー画像のS3 URL', null=True)),
                ('car_name', models.CharField(blank=True, help_text='愛車名前', max_length=200, null=True)),
                ('car_photo_front_url', models.URLField(blank=True, help_text='フロント写真のS3 URL', null=True)),
                ('car_photo_side_url', models.URLField(blank=True, help_text='サイド写真のS3 URL', null=True)),
                ('car_photo_rear_url', models.URLField(blank=True, help_text='リア写真のS3 URL', null=True)),
                ('car_photo_diagonal_url', models.URLField(blank=True, help_text='斜め前右写真のS3 URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '愛車設定',
                'verbose_name_plural': '愛車設定',
                'db_table': 'car_settings',
                'unique_together': {('user_id', 'car_id')},
            },
        ),
    ]
