# Generated by Django 5.2.3 on 2025-07-13 06:37

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_carsettings'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCharge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='ユーザーID')),
                ('charge_amount', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='チャージ金額')),
                ('credit_amount', models.IntegerField(verbose_name='付与クレジット')),
                ('stripe_payment_intent_id', models.CharField(max_length=255, unique=True, verbose_name='Stripe決済ID')),
                ('stripe_client_secret', models.CharField(blank=True, max_length=255, null=True, verbose_name='Stripeクライアントシークレット')),
                ('payment_status', models.CharField(choices=[('pending', '決済処理中'), ('succeeded', '決済成功'), ('failed', '決済失敗'), ('canceled', '決済キャンセル'), ('refunded', '返金済み')], default='pending', max_length=20, verbose_name='決済ステータス')),
                ('stripe_metadata', models.JSONField(blank=True, default=dict, verbose_name='Stripeメタデータ')),
                ('error_message', models.TextField(blank=True, null=True, verbose_name='エラーメッセージ')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='完了日時')),
            ],
            options={
                'verbose_name': 'クレジットチャージ',
                'verbose_name_plural': 'クレジットチャージ',
                'db_table': 'credit_charges',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='UserCredit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, unique=True, verbose_name='ユーザーID')),
                ('credit_balance', models.IntegerField(default=0, verbose_name='クレジット残高')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'ユーザークレジット',
                'verbose_name_plural': 'ユーザークレジット',
                'db_table': 'user_credits',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=100, verbose_name='ユーザーID')),
                ('transaction_type', models.CharField(choices=[('charge', 'チャージ'), ('usage', '使用'), ('refund', '返金'), ('bonus', 'ボーナス')], max_length=20, verbose_name='取引種別')),
                ('amount', models.IntegerField(verbose_name='クレジット金額')),
                ('balance_after', models.IntegerField(verbose_name='取引後残高')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='説明')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('charge', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.creditcharge', verbose_name='関連チャージ')),
            ],
            options={
                'verbose_name': 'クレジット取引履歴',
                'verbose_name_plural': 'クレジット取引履歴',
                'db_table': 'credit_transactions',
                'ordering': ['-created_at'],
            },
        ),
    ]
