# Generated by Django 5.2.3 on 2025-07-13 07:56

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_creditcharge_usercredit_credittransaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='Library',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='MyGarageユーザーID', max_length=100)),
                ('frontend_id', models.CharField(help_text='フロントエンドで使用するID', max_length=100)),
                ('image_url', models.URLField(help_text='生成画像のURL（GCS等）', max_length=1000)),
                ('display_prompt', models.TextField(help_text='表示用プロンプト')),
                ('menu_name', models.CharField(blank=True, help_text='使用したメニュー名', max_length=200, null=True)),
                ('used_form_data', models.JSONField(help_text='生成時に使用したフォームデータ（MenuExecutionFormData）')),
                ('rating', models.CharField(blank=True, choices=[('good', 'Good'), ('bad', 'Bad')], help_text='ユーザー評価', max_length=10, null=True)),
                ('is_public', models.BooleanField(default=False, help_text='公開設定')),
                ('author_name', models.CharField(blank=True, help_text='公開時の作者名', max_length=200, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('timestamp', models.DateTimeField(help_text='生成日時（フロントエンドのtimestampに対応）')),
            ],
            options={
                'db_table': 'api_library',
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['user_id', '-timestamp'], name='api_library_user_id_3eef46_idx'), models.Index(fields=['is_public', '-timestamp'], name='api_library_is_publ_5ef85e_idx'), models.Index(fields=['user_id', 'is_public'], name='api_library_user_id_418e03_idx'), models.Index(fields=['frontend_id'], name='api_library_fronten_16027a_idx')],
            },
        ),
    ]
