# Generated by Django 5.2.3 on 2025-07-13 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_library'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='library',
            unique_together={('user_id', 'frontend_id')},
        ),
    ]
