# Generated by Django 5.2.3 on 2025-07-13 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_alter_library_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='is_saved_to_library',
            field=models.BooleanField(default=False, help_text='ユーザーがライブラリに明示的に保存したかどうか'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['user_id', 'is_saved_to_library'], name='api_library_user_id_731bb3_idx'),
        ),
        migrations.AddIndex(
            model_name='library',
            index=models.Index(fields=['is_saved_to_library', '-timestamp'], name='api_library_is_save_b705a0_idx'),
        ),
    ]
