# Generated by Django 5.2.3 on 2025-07-14 13:08

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_add_library_flag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='MyGarageユーザーID', max_length=100)),
                ('user_name', models.CharField(help_text='コメント表示用のユーザー名', max_length=200)),
                ('content', models.TextField(help_text='コメント本文（500文字まで）', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='更新日時')),
                ('library', models.ForeignKey(help_text='コメント対象のライブラリ画像', on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='api.library')),
            ],
            options={
                'db_table': 'api_comment',
                'ordering': ['created_at'],
                'indexes': [models.Index(fields=['library', 'created_at'], name='api_comment_library_111a50_idx'), models.Index(fields=['user_id', '-created_at'], name='api_comment_user_id_86e7b0_idx'), models.Index(fields=['library', '-created_at'], name='api_comment_library_6bd888_idx')],
            },
        ),
        migrations.CreateModel(
            name='Like',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_id', models.CharField(help_text='MyGarageユーザーID', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='いいねした日時')),
                ('library', models.ForeignKey(help_text='いいね対象のライブラリ画像', on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='api.library')),
            ],
            options={
                'db_table': 'api_like',
                'indexes': [models.Index(fields=['library', 'user_id'], name='api_like_library_fc4c59_idx'), models.Index(fields=['user_id', '-created_at'], name='api_like_user_id_a16705_idx'), models.Index(fields=['library', '-created_at'], name='api_like_library_978e9c_idx')],
                'unique_together': {('library', 'user_id')},
            },
        ),
    ]
