# Generated by Django 5.2.3 on 2025-07-14 16:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_add_user_profile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_profil_fronten_37a106_idx',
            old_name='user_profil_fronten_6b6b44_idx',
        ),
        migrations.RenameIndex(
            model_name='userprofile',
            new_name='user_profil_is_admi_3674d2_idx',
            old_name='user_profil_is_admi_4e4e87_idx',
        ),
    ]
