# Generated by Django 5.2.3 on 2025-07-15 12:44

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_rename_user_profil_fronten_6b6b44_idx_user_profil_fronten_37a106_idx_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhoneUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('firebase_uid', models.CharField(db_index=True, max_length=128, unique=True)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('nickname', models.CharField(max_length=20)),
                ('is_admin', models.BooleanField(default=False)),
                ('credits', models.IntegerField(default=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': '電話番号ユーザー',
                'verbose_name_plural': '電話番号ユーザー',
                'db_table': 'phone_users',
            },
        ),
        migrations.CreateModel(
            name='PhoneVerificationSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(db_index=True, max_length=15)),
                ('verification_code', models.CharField(max_length=6)),
                ('session_id', models.CharField(db_index=True, max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '電話番号認証セッション',
                'verbose_name_plural': '電話番号認証セッション',
                'db_table': 'phone_verification_sessions',
            },
        ),
        migrations.CreateModel(
            name='PhoneLoginToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('token', models.CharField(db_index=True, max_length=100, unique=True)),
                ('expires_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('phone_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tokens', to='api.phoneuser')),
            ],
            options={
                'verbose_name': '電話番号ログイントークン',
                'verbose_name_plural': '電話番号ログイントークン',
                'db_table': 'phone_login_tokens',
            },
        ),
    ]
