# Generated by Django 5.2.3 on 2025-07-15 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_phoneuser_phoneverificationsession_phonelogintoken'),
    ]

    operations = [
        migrations.AddField(
            model_name='library',
            name='goods_creation_count',
            field=models.IntegerField(default=0, help_text='この画像を使ってグッズが作成された回数'),
        ),
    ]
