# Generated by Django 5.2.3 on 2025-07-16 00:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_add_goods_creation_count'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SuzuriMerchandise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('goods_creator_user_id', models.CharField(help_text='グッズを作った人のユーザーID（Firebase UID）', max_length=100)),
                ('original_image_creator_user_id', models.CharField(help_text='元画像を生成した人のユーザーID（Firebase UID）', max_length=100)),
                ('library_image_id', models.UUIDField(help_text='グッズを作った画像のLibrary ID')),
                ('frontend_user_id', models.CharField(blank=True, help_text='フロントエンドのユーザーID（後方互換性）', max_length=100)),
                ('product_id', models.BigIntegerField(help_text='SUZURI の商品ID')),
                ('material_id', models.BigIntegerField(help_text='SUZURI のマテリアルID')),
                ('product_title', models.CharField(help_text='商品タイトル', max_length=255)),
                ('product_url', models.URLField(help_text='SUZURI の商品ページURL')),
                ('sample_image_url', models.URLField(help_text='商品プレビュー画像URL')),
                ('original_image_url', models.URLField(help_text='元の生成画像URL')),
                ('car_name', models.CharField(help_text='車の名前', max_length=100)),
                ('description', models.TextField(blank=True, help_text='商品説明')),
                ('item_name', models.CharField(help_text='アイテム名（例：heavyweight-t-shirt）', max_length=100)),
                ('item_id', models.IntegerField(help_text='SUZURI のアイテムID')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='グッズ作成日')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='suzuri_merchandise', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'suzuri_merchandise',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['goods_creator_user_id', '-created_at'], name='suzuri_merc_goods_c_ba4e45_idx'), models.Index(fields=['original_image_creator_user_id', '-created_at'], name='suzuri_merc_origina_a3ac62_idx'), models.Index(fields=['library_image_id'], name='suzuri_merc_library_9c393c_idx'), models.Index(fields=['product_id'], name='suzuri_merc_product_49424d_idx'), models.Index(fields=['frontend_user_id', '-created_at'], name='suzuri_merc_fronten_f280f3_idx')],
            },
        ),
    ]
