# Generated by Django 5.2.3 on 2025-07-17 08:11

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_suzurimerchandise'),
    ]

    operations = [
        migrations.CreateModel(
            name='ChargeOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='オプション名')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='説明')),
                ('price_yen', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='価格（円）')),
                ('credits_awarded', models.IntegerField(verbose_name='付与クレジット')),
                ('credits_bonus', models.IntegerField(default=0, verbose_name='ボーナスクレジット')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('is_active', models.BooleanField(default=True, verbose_name='有効フラグ')),
                ('is_popular', models.BooleanField(default=False, verbose_name='人気オプション')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'チャージオプション',
                'verbose_name_plural': 'チャージオプション',
                'db_table': 'charge_options',
                'ordering': ['display_order', 'price_yen'],
            },
        ),
        migrations.AlterField(
            model_name='phoneuser',
            name='credits',
            field=models.IntegerField(default=30),
        ),
    ]
