# Generated by Django 5.2.3 on 2025-07-17 18:06

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_add_category_order_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['order_index', 'id']},
        ),
        migrations.RemoveField(
            model_name='phoneuser',
            name='credits',
        ),
        migrations.AddField(
            model_name='userprofile',
            name='nickname',
            field=models.CharField(blank=True, max_length=100, verbose_name='ニックネーム'),
        ),
        migrations.CreateModel(
            name='MyGarageUser',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('mygarage_user_id', models.CharField(db_index=True, help_text='MyGarageシステムのユーザーID', max_length=100, unique=True)),
                ('email', models.EmailField(help_text='MyGarageアカウントのメールアドレス', max_length=254)),
                ('name', models.CharField(help_text='MyGarageアカウントの名前', max_length=200)),
                ('is_admin', models.BooleanField(default=False, help_text='AISHA管理者フラグ')),
                ('credits', models.IntegerField(default=100, help_text='AISHAクレジット残高（MyGarage認証では100クレジット）')),
                ('last_login_token', models.CharField(blank=True, help_text='最後のログイントークン', max_length=500)),
                ('last_token_expires', models.DateTimeField(blank=True, help_text='トークンの有効期限', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='AISHA初回ログイン日時')),
                ('updated_at', models.DateTimeField(auto_now=True, help_text='最終更新日時')),
                ('last_login', models.DateTimeField(blank=True, help_text='最終ログイン日時', null=True)),
            ],
            options={
                'verbose_name': 'MyGarageユーザー',
                'verbose_name_plural': 'MyGarageユーザー',
                'db_table': 'mygarage_users',
                'indexes': [models.Index(fields=['mygarage_user_id'], name='mygarage_us_mygarag_1ce3c0_idx'), models.Index(fields=['email'], name='mygarage_us_email_e319e2_idx'), models.Index(fields=['is_admin'], name='mygarage_us_is_admi_5b9d3a_idx')],
            },
        ),
        migrations.CreateModel(
            name='MyGarageCreditTransaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('initial', '初回登録ボーナス'), ('consume', 'クレジット消費'), ('purchase', 'クレジット購入'), ('admin_add', '管理者追加'), ('admin_subtract', '管理者減算')], help_text='取引種別', max_length=20)),
                ('amount', models.IntegerField(help_text='取引金額（正数：追加、負数：消費）')),
                ('description', models.CharField(help_text='取引説明', max_length=500)),
                ('balance_before', models.IntegerField(help_text='取引前残高')),
                ('balance_after', models.IntegerField(help_text='取引後残高')),
                ('related_menu_id', models.IntegerField(blank=True, help_text='関連するメニューID', null=True)),
                ('related_image_url', models.URLField(blank=True, help_text='関連する画像URL', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='取引日時')),
                ('mygarage_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='api.mygarageuser')),
            ],
            options={
                'verbose_name': 'MyGarageクレジット取引',
                'verbose_name_plural': 'MyGarageクレジット取引',
                'db_table': 'mygarage_credit_transactions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['mygarage_user', 'created_at'], name='mygarage_cr_mygarag_b86f6b_idx'), models.Index(fields=['transaction_type'], name='mygarage_cr_transac_fe10ed_idx'), models.Index(fields=['created_at'], name='mygarage_cr_created_a2e672_idx')],
            },
        ),
    ]
