# Generated by Django 5.2.3 on 2025-07-18 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_alter_category_options_remove_phoneuser_credits_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='phoneverificationsession',
            name='attempts',
            field=models.IntegerField(default=0),
        ),
    ]
