# Generated by Django 5.2.3 on 2025-07-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_phoneverificationsession_attempts'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsManagement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('supplier', models.CharField(choices=[('suzuri', 'SUZURI'), ('printful', 'Printful'), ('spreadshirt', 'Spreadshirt')], default='suzuri', max_length=50, verbose_name='サプライヤー')),
                ('suzuri_item_id', models.IntegerField(verbose_name='SUZURIアイテムID')),
                ('item_name', models.CharField(max_length=255, verbose_name='アイテム名')),
                ('display_name', models.CharField(max_length=255, verbose_name='表示名')),
                ('display_order', models.IntegerField(default=0, verbose_name='表示順序')),
                ('icon_url', models.TextField(blank=True, null=True, verbose_name='アイコン画像URL')),
                ('sample_image_url', models.TextField(blank=True, null=True, verbose_name='サンプル画像URL')),
                ('descriptions', models.JSONField(default=list, verbose_name='商品説明文')),
                ('base_price', models.IntegerField(default=0, verbose_name='基本価格')),
                ('profit_margin', models.IntegerField(default=0, verbose_name='追加利益')),
                ('available_print_places', models.JSONField(default=list, verbose_name='利用可能なプリント位置')),
                ('is_multi_printable', models.BooleanField(default=False, verbose_name='複数箇所プリント可能')),
                ('is_public', models.BooleanField(default=False, verbose_name='公開フラグ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': 'グッズ管理',
                'verbose_name_plural': 'グッズ管理',
                'db_table': 'goods_management',
                'ordering': ['display_order', 'id'],
                'unique_together': {('supplier', 'suzuri_item_id')},
            },
        ),
    ]
