# Generated by Django 5.2.3 on 2025-07-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_goodsmanagement'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmanagement',
            name='api_config',
            field=models.JSONField(default=dict, help_text='SUZURI APIに送信する際の商品タイプ別パラメータ設定', verbose_name='API送信データ設定'),
        ),
        migrations.AddField(
            model_name='goodsmanagement',
            name='item_type',
            field=models.CharField(default='heavyweight-t-shirt', help_text='SUZURI APIで使用する商品タイプ識別子', max_length=100, verbose_name='商品タイプ'),
        ),
    ]
