# Generated by Django 5.2.3 on 2025-07-19 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_goodsmanagement_api_config_goodsmanagement_item_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='goodsmanagement',
            name='needs_sub_materials',
            field=models.BooleanField(default=False, help_text='SUZURI APIでsub_materialsパラメータが必要かどうか', verbose_name='sub_materials必要フラグ'),
        ),
    ]
