# Generated by Django 5.2.3 on 2025-07-19 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_goodsmanagement_needs_sub_materials'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_intent_id', models.CharField(help_text='Stripe Payment Intent ID', max_length=255, verbose_name='Payment Intent ID')),
                ('status', models.CharField(choices=[('pending', '処理中'), ('success', '成功'), ('failed', '失敗'), ('cancelled', 'キャンセル')], max_length=20, verbose_name='決済状態')),
                ('amount', models.IntegerField(help_text='決済金額（円単位）', verbose_name='金額（円）')),
                ('currency', models.CharField(default='jpy', help_text='ISO通貨コード（例: jpy, usd）', max_length=3, verbose_name='通貨')),
                ('customer_id', models.CharField(blank=True, help_text='Stripe Customer ID', max_length=255, null=True, verbose_name='顧客ID')),
                ('error_message', models.TextField(blank=True, help_text='決済失敗時のエラーメッセージ', null=True, verbose_name='エラーメッセージ')),
                ('webhook_event_type', models.CharField(blank=True, help_text='Stripe Webhookイベントタイプ', max_length=100, null=True, verbose_name='Webhookイベントタイプ')),
                ('raw_data', models.JSONField(blank=True, help_text='Stripeからの生Webhookデータ', null=True, verbose_name='生データ')),
                ('processed', models.BooleanField(default=False, help_text='決済結果の処理が完了したかどうか', verbose_name='処理済み')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
            ],
            options={
                'verbose_name': '決済ログ',
                'verbose_name_plural': '決済ログ',
                'db_table': 'payment_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['payment_intent_id'], name='payment_log_payment_cea283_idx'), models.Index(fields=['status'], name='payment_log_status_d17c09_idx'), models.Index(fields=['created_at'], name='payment_log_created_7a2b3a_idx'), models.Index(fields=['customer_id'], name='payment_log_custome_b08274_idx')],
            },
        ),
    ]
