# Generated by Django 5.2.3 on 2025-07-20 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0020_paymentlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_login_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='最終ログイン日時'),
        ),
    ]
