# Generated by Django 5.2.3 on 2025-07-20 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0021_userprofile_last_login_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='menu',
            name='display_order',
            field=models.IntegerField(default=0, help_text='表示順序（小さい順に表示）'),
        ),
    ] 