# Generated by Django 5.2.3 on 2025-08-01 01:50

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_add_display_order_to_menu'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicComment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('frontend_id', models.CharField(db_index=True, max_length=255)),
                ('content', models.TextField(max_length=500)),
                ('author_name', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [
                    models.Index(fields=['frontend_id', '-created_at'], name='api_publicc_fronten_8c5f69_idx'),
                ],
            },
        ),
    ]
