FROM python:3.11

ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

WORKDIR /app

COPY requirements.txt /app/
RUN pip install --upgrade pip && pip install -r requirements.txt

COPY . /app/

# Firebase認証ファイルをコピー
COPY service-account.json /app/service-account.json

ENV PORT=8080
EXPOSE 8080

CMD ["gunicorn", "django_project.wsgi:application", "--bind", "0.0.0.0:8080", "--workers", "2"]