name: Deploy DB Test Only

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: aisha-462412
  REGION: asia-northeast1

jobs:
  deploy:
    name: Deploy DB Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Deploy Backend Test
      run: |
        gcloud run deploy aisha-backend-test \
          --source ./pycharm_project \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --memory 1Gi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --set-env-vars DEBUG=False \
          --set-env-vars DJANGO_SECRET_KEY=${{ secrets.DJANGO_SECRET_KEY }} \
          --set-env-vars DATABASE_URL=postgresql://postgres:postgres@34.85.116.154:5432/postgres \
          --set-env-vars ALLOWED_HOSTS=*.run.app

    - name: Get Backend URL
      run: |
        BACKEND_URL=$(gcloud run services describe aisha-backend-test --region ${{ env.REGION }} --format 'value(status.url)')
        echo "Backend URL: $BACKEND_URL"
        echo "Test URL: $BACKEND_URL/api/db-test/" 