name: Minimal DB Test

on:
  push:
    branches: [ main ]
  workflow_dispatch:

env:
  PROJECT_ID: aisha-462412
  REGION: asia-northeast1

jobs:
  deploy:
    name: Deploy Minimal DB Test
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Set up Google Cloud CLI
      uses: google-github-actions/setup-gcloud@v2
      with:
        project_id: ${{ env.PROJECT_ID }}

    - name: Deploy Minimal DB Test
      run: |
        gcloud run deploy aisha-db-test-minimal \
          --source . \
          --platform managed \
          --region ${{ env.REGION }} \
          --allow-unauthenticated \
          --memory 512Mi \
          --cpu 1 \
          --min-instances 0 \
          --max-instances 10 \
          --set-env-vars PORT=8080

    - name: Get URL
      run: |
        URL=$(gcloud run services describe aisha-db-test-minimal --region ${{ env.REGION }} --format 'value(status.url)')
        echo "Test URL: $URL" 